project:
  type: site
  title: "Hinterland Harbor"
  output-dir: ./_site

site:
  title: "Quarto + RMD + Github Pages Test"
  sharing: [twitter, facebook, linkedin]
  repo-url: https://github.com/pommevilla/hinterland-harbor

  navbar:
    background: "dark"
    right:
      - text: "Home"
        href: index.qmd
      - text: "Sample biodiversity analysis in R"
        href: sample_analysis.Rmd
      - text: "A simple Python notebook"
        href: sample_python.ipynb
      - text: "More about Quarto"
        menu:
        - text: "Quarto.org"
          url: https://quarto.org/
        - text: "quarto-render Github action"
          url: https://github.com/pommevilla/quarto-render
      - icon: github
        href: https://github.com/pommevilla/hinterland-harbor

format:
  html:
    theme: cosmo
    code-background: true
    css: styles.css
    toc: true
